### PR TITLE
fix add profile conditions

### LINKED ISSUE #414: Add profile conditions not working
**Description**
Cannot add new group to profile in settings page. Clicking the 'Add Group' button does nothing.
Steps to reproduce: 
1. Build a fresh installment of yomitan from (latest) source
2. Open settings page > Configure profiles... > Conditions > Add Group

image

**Browser version**
Version 120.0.6099.110 (Official Build) (64-bit)

**Yomitan version**
Built from source

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

### PR DESCRIPTION
**Pull request by Scrub1492**
This change resolves #414 . 
I believe this bug is caused by #364 . However, I am not sure if this solution captures every instance caused by this change. 
@toasted-nutbread thoughts?

### CODE REVIEW

**Comment by toasted-nutbread** [comment]
Presumably this is due to elements not existing in certain contexts. If that's the case, mark the type as nullable and omit the cast.

```
/** @type {?HTMLButtonElement} */
this._menuButton = this._node.querySelector('.profile-condition-menu-button');
```

**Comment by toasted-nutbread** [comment]
That being said, this is probably another case of legacy code never being fully removed. If you search for `profile-condition-remove` in the codebase, it only comes up in one place: the code that is being modified here. This indicates that the element actually doesn't exist, and all codepaths involving this field should just be deleted.

**Comment by toasted-nutbread** [comment]
For `_conditionContainer`, you can leave that as the `NotNull` version and just remove any subsequent null checks. Same for `_menuButton`.


The reason these dead codepaths and unnecessary checks exist is because there was a massive UI overhaul of the settings page a long time ago, and the same classes would drive both versions of the settings page for the time they co-existed.

**Comment by Scrub1492** [comment]
Thanks. I included the changes.

**Review by djahandarie — APPROVED** [review]

**Pull request merged**
