### PR TITLE
Add search settings modal

### PR DESCRIPTION
**Pull request by Kuuuube**
|     |       |
| ------------- | ------------- |
| image | image |

Open to suggestions for the ui. Moving the cog to the right isnt reasonable since mobile users are likely to accidentally click it when trying to search.

### CODE REVIEW

**Comment by jamesmaa** [comment]
> Open to suggestions for the ui. Moving the cog to the right isnt reasonable since mobile users are likely to accidentally click it when trying to search.

Why not put it to the right of the yomitan search header?

**Comment by Kuuuube** [comment]
> Why not put it to the right of the yomitan search header?

Are you suggesting that we hide the settings cog after a user searches a word? The yomitan search header is only there when the page is initially opened or after the user searches while the search is empty.

**Comment by jamesmaa** [comment]
Oh you're right. Putting the cog on the left just really throws me off. Can you say a little more about what you mean by " mobile users are likely to accidentally click it when trying to search."?

**Comment by Kuuuube** [comment]
This is what it looks like with the cog aligned to the right on mobile:
image

It is way too close to the search button for mobile. Very easy to accidentally tap.

**Comment by Kuuuube** [comment]
Made a few changes this is how it looks now.

image
image

**Review by jamesmaa — APPROVED** [review]
I don't think I'll be able to review it thoroughly but since these are mostly frontend changes I'm happy to merge and do fast fixes if anything comes up

**Pull request merged**
