### PR TITLE
Add benchmarks for Translator class methods

### PR DESCRIPTION
**Pull request by Scrub1492**
Creates some benchmarks for some translator functions. See https://github.com/themoeway/yomitan/pull/584#issuecomment-1930453829

### CODE REVIEW

**Comment by Scrub1492** [comment]
(I don't actually know what void window is doing, so if its redundant please tell)

**Comment by toasted-nutbread** [comment]
> (I don't actually know what `void window` is doing, so if its redundant please tell)

You can try removing it and see if it breaks, but it's basically just doing a no-op on the window variable so it doesn't get flagged as unused. It's either do that or add an // lint-ignore comment, but the {window} needs to be present so that it initializes the virtual DOM. This is usually needed for structured content testing. If the test doesn't need the virtual DOM, it can be removed.

**Comment by toasted-nutbread** [comment]
In this case, I bet you can remove `window` altogether.

**Comment by Scrub1492** [comment]
> > (I don't actually know what `void window` is doing, so if its redundant please tell)
> 
> You can try removing it and see if it breaks, but it's basically just doing a no-op on the window variable so it doesn't get flagged as unused. It's either do that or add an // lint-ignore comment, but the {window} needs to be present so that it initializes the virtual DOM. This is usually needed for structured content testing. If the test doesn't need the virtual DOM, it can be removed.

It seems that it is needed for the AnkiTemplateRenderer to work in `dictionary-data.test.js`, and its fine to remove in this case. Thanks for clearing up the confusion.

**Comment by Scrub1492** [comment]
I don't have any plans yet to make a bench for `AnkiTemplateRenderer` or `createNoteAnkiData()`, as I feel like benches should be relevant and I'm not sure yet if these needs a bench. I'll keep this PR to `Translator` functions, but please let me know if these are needed.

**Comment by toasted-nutbread** [comment]
I wouldn't be too worried about those methods currently, as it's a user-invoked action.

**Review by toasted-nutbread — APPROVED** [review]

**Review by djahandarie — APPROVED** [review]

**Pull request merged**
