### PR TITLE
[ko] Fix -ida transforms

### PR DESCRIPTION
**Pull request by Casheeew**
- Fixes [some issues with -ida transforms such as 이어야 or 이어야만 not deinflecting to postpositional particle 이다](https://discord.com/channels/617136488840429598/1054623093416529940/1262965861191516170)
- fix typo
- fix 이는 incorrectly deinflecting to postpositional particle 이다, should be 인
- add 예요 deinflection

### CODE REVIEW

**Review by jamesmaa — APPROVED** [review]
If you want a rubber stamp

**Comment by Casheeew** [comment]
@Lyroxide :nanabeg:

**Comment by Lyroxide** [comment]
Looks good

**Review by Kuuuube — APPROVED** [review]
Approving for lyroxide

**Pull request merged**
