### PR TITLE
preserve whitespace in cloze-prefix and cloze-suffix

### LINKED ISSUE #744: English support issue
**Description**
I mine word convene and html for the sentence field looks like this
```hearings are<b>convene</b>d,```
spaces are not respected.
anki_2024_02_29_10_53_44_948_VymPaRzKNB
I figured something wrong with yomitan's anki template settings {cloze-prefix}<b>{cloze-body}</b>{cloze-suffix}
Any help? 

**Browser version**
chrome 122.0.6261.95

**Yomitan version**
24.2.26.0

**Exported settings file**
[yomitan-settings-2024-02-29-15-19-19.json](https://github.com/themoeway/yomitan/files/14449931/yomitan-settings-2024-02-29-15-19-19.json)

### PR DESCRIPTION
**Pull request by StefanVukovic99**
Fixes #744 
Basically, it seems the handlebars `~` removes whitespace but not newlines. Instead of trimming the string outputted by handlebars this just removes the newlines.

### CODE REVIEW

**Comment by Kuuuube** [comment]
Note that this will have conflicts with #733.

**Review by djahandarie — APPROVED** [review]

**Comment by kuroahna** [comment]
Hi @StefanVukovic99 I think this needs a 2nd look. It's broken other handlebars templates now such as `{expression}` and `{reading}`.

In Anki Card Templates, I have
1. Scanned text = 読め
2. Card field = `{expressino}`
And then I click `Test`

The card render.result returns me

```







読める
```

with a lot of newlines

**Comment by StefanVukovic99** [comment]
That is strange
Screenshot from 2024-03-04 21-15-36
Screenshot from 2024-03-04 21-15-47
Any other info? Does it do the same when you add the card to anki?

**Comment by kuroahna** [comment]
Sorry for the noise @StefanVukovic99 , I reverted to the default template and it works. I had
```
        {{#each glossary}}{{#formatGlossary ../dictionary}}{{#regexReplace "^[^\n]*\n" ""}}{{{.}}}{{/regexReplace}}{{/formatGlossary}}{{/each}}
```

in

```
{{#*inline "glossary-single"}}
    {{~#unless brief~}}
        {{~#scope~}}
            {{~set "any" false~}}
            {{~#each definitionTags~}}
                {{~#if (op "||" (op "!" @root.compactTags) (op "!" redundant))~}}
                    {{~#if (get "any")}}, {{else}}<i>({{/if~}}
                    {{name}}
                    {{~set "any" true~}}
                {{~/if~}}
            {{~/each~}}
            {{~#unless noDictionaryTag~}}
                {{~#if (op "||" (op "!" @root.compactTags) (op "!==" dictionary (get "previousDictionary")))~}}
                    {{~#if (get "any")}}, {{else}}<i>({{/if~}}
                    {{dictionary}}
                    {{~set "any" true~}}
                {{~/if~}}
            {{~/unless~}}
            {{~#if (get "any")}})</i> {{/if~}}
        {{~/scope~}}
        {{~#if only~}}({{#each only}}{{.}}{{#unless @last}}, {{/unless}}{{/each}} only) {{/if~}}
    {{~/unless~}}
    {{~#if (op "<=" glossary.length 1)~}}
        {{#each glossary}}{{#formatGlossary ../dictionary}}{{#regexReplace "^[^\n]*\n" ""}}{{{.}}}{{/regexReplace}}{{/formatGlossary}}{{/each}}
    {{~else if @root.compactGlossaries~}}
        {{#each glossary}}{{#formatGlossary ../dictionary}}{{#regexReplace "^[^\n]*\n" ""}}{{{.}}}{{/regexReplace}}{{/formatGlossary}}{{#unless @last}} | {{/unless}}{{/each}}
    {{~else~}}
        <ul>{{#each glossary}}<li>{{formatGlossary ../dictionary .}}</li>{{/each}}</ul>
    {{~/if~}}
    {{~set "previousDictionary" dictionary~}}
{{/inline}}
```

from an old handlebars template I copied.

**Pull request merged**
