### PR TITLE
add some Japanese transforms

### PR DESCRIPTION
**Pull request by Lyroxide**
Reference: https://tsukuba.repo.nii.ac.jp/record/3420/files/5.pdf

-rya is the -ba contraction, I can't think of any better romaji names. maybe '-ya' is better?

-cha is -ては contraction. usually it's followed by いけない, so "行っちゃいけない" gets highlighted as 行っちゃい (-chau < masu stem) which is incorrect. "行っちゃだめ" won't even show the plain form

-n usually appears in -んばかり, like いわんばかり

### CODE REVIEW

**Comment by jamesmaa** [comment]
Btw you'll have to update after we merged #784

**Comment by Lyroxide** [comment]
@djahandarie Would need your review 🙏

**Comment by StefanVukovic99** [comment]
As the pdf says, the -rya contraction for verbs is pretty rare but there's no harm in having it I guess. Should 帰らなきゃ and such also be supported? Also, what do you think about, instead of having it deinflect directly to the dictionary form, going to -ba, like:
```js
suffixInflection('けりゃ', 'ければ', [], ['ba']) // adding intermediate rule for ba
```
image. 
For naming, since the `r` sound is not always there, `ya`, `(r)ya`. If doing the chaining with -ba, maybe naming it `ba -> (r)ya` instead of `contraction`.

I don't see this kind of -n for verbs mentioned in the pdf, but I think it's good, since we currently have nothing for 話さんか and such. 

-cha is good i think. 行っちゃいけない will still try and match the longest string, so it will say chau + masu, but that's a separate issue we should hopefully fix soon (should also start showing the descriptions on hover, maybe also which text preprocessing was applied)

**Comment by Lyroxide** [comment]
I think chaining -ba -> -ya sounds good
> 帰らなきゃ

yeah I forgot about that one. will add that in

> rare

i think it's pretty common especially for ければ->けりゃ and れば->りゃ. but tbf I don't know if I have ever seen the rest, like 待ちゃ (???)

**Review by StefanVukovic99 — APPROVED** [review]

**Pull request merged**
