### PR TITLE
Fix chromium clipboard access

### PR DESCRIPTION
**Pull request by jbukl**
I moved from yomichan to this yesterday and was having issues with how I usually mine cards because the clipboard monitor for the search page wasn't working, so I fixed it locally.
Feel free to close this if this is duplicated work or there's a nicer solution in mind.

* handle clipboard requests via offscreen document (https://developer.chrome.com/docs/extensions/reference/offscreen/)
* default to the usual handling of clipboard backend calls with ClipboardReader.getText when chrome.offscreen isn't available

### CODE REVIEW

**Comment by djahandarie** [comment]
@jbukl Thank you so much for the PR. I believe @praschke is working on a solution here using offscreen as well, so let us wait for his input as well.

**Review by praschke — COMMENTED** [review]
besides the comments i left, there are three other issues.

- getImage is not implemented by this change, so #269 would not be fixed.
- the contents of the offscreen directory should instead go in the background directory.
- the offscreen permission should be documented in `docs/permissions.md`.

**Review by djahandarie — APPROVED** [review]

**Review by djahandarie — APPROVED** [review]
Thanks for all the fixes. LGTM!

**Comment by praschke** [comment]
this should close #71, #165, #269, #275.

**Pull request merged**
