### PR TITLE
Add vitest benchmark

### PR DESCRIPTION
**Pull request by Scrub1492**
First step to #87 . Adds some benchmarks for high bandwidth functions.
However, vitest benchmark is still experimental, so not sure about maintainers' thoughts.

### CODE REVIEW

**Comment by djahandarie** [comment]
Very interesting, thanks! Maybe we could also consider using something like https://codspeed.io/blog/vitest-bench-performance-regressions ? (It seems to be free for OSS projects and looks more like the desired experience we would want on PRs. But I haven't looked at other potential solutions, it just came up from basic Google searching)

**Comment by Scrub1492** [comment]
> Very interesting, thanks! Maybe we could also consider using something like https://codspeed.io/blog/vitest-bench-performance-regressions ? (It seems to be free for OSS projects and looks more like the desired experience we would want on PRs. But I haven't looked at other potential solutions, it just came up from basic Google searching)

Can you setup the action in the CI?

**Comment by djahandarie** [comment]
@Scrub1492 I did the setup on the Codspeed side, and added the CODSPEED_TOKEN within our CI. Would you be able to add the contents of the action here: https://docs.codspeed.io/ci/github-actions to your PR?

**Comment by Scrub1492** [comment]
weird, it was working locally

**Comment by Scrub1492** [comment]
Does anyone have any idea what's breaking? not too familiar with github workflows 😅

**Comment by toasted-nutbread** [comment]
> Benchmarking is an experimental feature.
> Breaking changes might not follow SemVer, please pin Vitest's version when using it.

Something from the [CI logs](https://github.com/themoeway/yomitan/actions/runs/7764168520/job/21177561621#step:6:337). Based on this, if you get this working, we may want to do two things:

1. Update the vitest dependencies manually to the latest version (see #612) and pin them.
2. Test to make sure it works with the latest version.

**Comment by djahandarie** [comment]
https://github.com/CodSpeedHQ/codspeed-node/tree/main/packages/vitest-plugin:
> The CodSpeed plugin is only compatible with [vitest@1.2.2](https://www.npmjs.com/package/vitest/v/1.2.2) and above.

I believe this branch is still on vitest 1.1.1 because it's not on top of #612

**Review by djahandarie — APPROVED** [review]

**Pull request merged**
