### PR TITLE
Style updates

### PR DESCRIPTION
**Pull request by Scrub1492**

### CODE REVIEW

**Review by djahandarie — CHANGES_REQUESTED** [review]
de/lib/handlebars is just a vendored copy of kbn's handlebars so we probably shouldn't make changes here. Rest looks fine

**Comment by Scrub1492** [comment]
I left changes to comments from yomitan developers, such as "liftet from handlebars/..." -> "Lifted from handlebars/..."

**Comment by djahandarie** [comment]
Those aren't our comments, they are kbn's comments for the stuff they lifted from handlebars proper.

**Comment by Scrub1492** [comment]
Oh, I didn't realize that, sorry.

**Comment by Scrub1492** [comment]
It should be fine now after a squash and merge

**Review by djahandarie — APPROVED** [review]

**Pull request merged**
