### PR TITLE
add lingua libre audio source

### LINKED ISSUE #1093: Add Lingua Libre as default audio source
Lingua Libre is a language recording (recently also videos for sign languages) website created by Wikimedia France. Recording made with it are available under one of three free licences selected by the recorder (CC0 1.0 Public Domain Dedication; Creative Commons Attribution ShareAlike 4.0; Creative Commons Attribution 4.0) and are mostly used in Wiktionaries and other Wikimedia projects.

As of 20 June they have 1,258,620 recording available in a variety of languages.
Three biggest are:
- French 383,693 recordings
- Odia 130,766 recordings
- Telugu 97,245 recordings

Full stats are available here https://lingualibre.org/wiki/LinguaLibre:Stats/Languages

Considering that Yomitan starts to support more and more languages, it would be great if we also provided an audio source for them.
Though in the current state, Lingua Libre still doesn't cover a lot of words for many languages. But anyone can contribute their recordings if they know the language, so both projects might benefit from the integration.

### PR DESCRIPTION
**Pull request by StefanVukovic99**
Closes #1093 

@hugolpz thanks for the fiddle, it was super helpful :kneeling_man: I have some more questions, please answer if you can (or point to documentation) :pray: :
- Search for [Hund](https://commons.wikimedia.org/w/api.php?action=query&format=json&list=search&srsearch=\-Hund.wav&srnamespace=6&origin=*) returns both German and Norwegian entries - can the search filter by language?
    - I've noticed the files for german have `deu` in the title, is this a hard rule so we can filter on that?
    - Are languages consistently referred to by their ISO 639-3 code?
-
    ```
    const searchString = `-${searchWord}.wav`;
    ```
    I've tried looking up for `.ogg` instead and there are also results. What formats are in use, is there a convenient way to search for all formats at once, or do we need to merge results from multiple requests?
    
- Searching for [lesen](https://commons.wikimedia.org/w/api.php?action=query&format=json&list=search&srsearch=\-lesen.wav&srnamespace=6&origin=*) returns a bunch of pdf's with titles that don't even contain `lesen`. Can the search be more exact?

- We already have reliable audio sources for Japanese, but is there anything in place on LL's side for languages with ambiguous writing systems? E.g. for Japanese, we use a "term+reading" system so we can differentiate between `生業(なりわい)` and `生業(せいぎょう)`.

### CODE REVIEW

**Comment by hugolpz** [comment]
Hello {},

### Commons lexical audio assets : categories and files. 
Commons is a crowd sourced project, so there are much more audio, but contributed in a chaotic ways. On the other hand, Lingualibre audios may make up to 30% of the audio words, but with strict categories names and filenames conventions.

You will need an hard coded table of `categories + iso` pairs together with `.ext` flexibility for the first approach. For lingualibre categories and files you may go with a simpler `common category name string + iso` rules, while all uploaded as `.wav`. This strategy is up to you.

### Filter per language
As pointed out in #1093 : yes we can. We need to refine the API request further. Allow me to put those examples bellow to explore those files data and try other API request formats.

Lingualibre files : 
- [File:LL-Q188 (deu)-Djknusper-Hund.wav](https://commons.wikimedia.org/wiki/File:LL-Q188 (deu)-Djknusper-Hund.wav) 
- [File:LL-Q9043 (nor)-Teodor605-hund.wav](https://commons.wikimedia.org/wiki/File:LL-Q9043 (nor)-Teodor605-hund.wav) 
- [File:LL-Q188 (deu)-CamelCaseNick-Hund.wav](https://commons.wikimedia.org/wiki/File:LL-Q188 (deu)-CamelCaseNick-Hund.wav) 
- [File:LL-Q131339 (gsw)-Mathieu Kappler-Hund.wav](https://commons.wikimedia.org/wiki/File:LL-Q131339 (gsw)-Mathieu Kappler-Hund.wav)

Non-Lingualibre files :
- TBC.

**Comment by hugolpz** [comment]
@StefanVukovic99 , I was able to refine the query centered on Commons' Lingualibre categories. See : 
- https://jsfiddle.net/6rbcu1yw/1/
- Input : Commons API URL + iso639-3 + word
- Response: List of relevant Commons Lingua Libre audio files

Note: this research is per Language + end of string. So a research for `eng` + `-green.wav` could also return `eng` + `blue-green.wav`.

### Wikibase `P407:Language of work` approach
> We could also look for audio pronunciation files with in [P407:language of work or name](https://www.wikidata.org/wiki/Special:EntityPage/P407) --> [Q188:German](https://www.wikidata.org/wiki/Special:EntityPage/Q188)
and [P9533:audio transcription](https://www.wikidata.org/wiki/Special:EntityPage/P9533) --> hund/Hund . (Query to find)

Current structured data is not open to external queries. So this method don't have API endpoint at the moment. 

Only this approach would allow an exact match for word queries, while also able to search in a `Language of work`.

**Comment by hugolpz** [comment]
@StefanVukovic99 : I added some sample.

**Comment by StefanVukovic99** [comment]
Thank you very much :pray: 
I'm happy with how this works now, it's ready for a review & merge.

I think to make use of some of the other Commons files it would be best to add another, `Wikimedia Commons` audio source that will use a different regex(es) to get some of the less systematically named files. That way `Lingua Libre` can be the 'quality' source and the rest of commons the 'quantity' source.

**Review by cashewnuttynuts — APPROVED** [review]
lgtm

**Review by Kuuuube — APPROVED** [review]

**Pull request merged**
