### PR TITLE
separate json test out of test-code

### PR DESCRIPTION
**Pull request by StefanVukovic99**
The JSON test takes a lot longer than the rest of `test-code`, which is annoying when trying to iterate and test some changes repeatedly.
image

### CODE REVIEW

**Review by toasted-nutbread — APPROVED** [review]

**Comment by djahandarie** [comment]
I think we will need to update https://github.com/themoeway/yomitan/blob/master/.github/workflows/ci.yml too because it calls test-json directly for some reason. Maybe it should just be changed to call `test` directly.. (not sure why it wasn't written like that originally, it's from the yomichan era)

**Comment by toasted-nutbread** [comment]
I think it's like that so it can run them all in parallel and not just running the npm test command because `npm test` will stop if anything fails, due to the `&&`. The CI runs them in parallel so this won't happen.

**Comment by djahandarie** [comment]
> I think it's like that so it can run them all in parallel and not just running the npm test command because npm test will stop if anything fails, due to the &&. The CI runs them in parallel so this won't happen.

While that would make totally sense, it's unfortunately not how it works. :sweat_smile: 
Steps within a single job run sequentially, and stop running on error (unless you put in some extra logic to tell it to keep running after an error, but even then it's still sequentual).

For example:
https://github.com/themoeway/yomitan/actions/runs/7864258074/job/21455786647

I would like to speed up the CI a bit so maybe we should split it up into separate jobs which run in parallel, though.

**Comment by toasted-nutbread** [comment]
Well that was maybe what I was _intending_ to try to do, but lord knows I am an expert at not doing things correctly. ¯\\\_(ツ)_/¯

**Review by djahandarie — APPROVED** [review]

**Pull request merged**
