### PR TITLE
Refactor Japanese ます, んかった form

### PR DESCRIPTION
**Pull request by khaitruong922**
**1. Refactor masu form**

*Problems*

- Currently there are many wrong conjugations with masu form, for example:
  - 行きまさない (masu -> negative)
  - 行きますな (masu -> imperative negative)
  - 行きましたい (masu -> tai)
 
- Verbs end with ます also is also treated as polite ます form
  - 済ません returns (negative) and (potential -> n). (negative) is incorrect, it should be 済まさない.
  - 済ましょう returns (volitional), which is incorrect, should be 済まそう.

Some may not appear in real text, but it can create wrong impressions on Japanese grammar for learners, especially when they start to output on their own.

*Solution*
- Remove `v5m`, add `masu` and `masen` conditions. 
masu form is a special form in Japanese with different rules of conjugation and we should not treat it as a godan verb. 

- Follow the conjugation rules in https://en.wiktionary.org/wiki/Appendix:Japanese_verbs
Only add universal rules: ません、ませんでした、ました、ましたら、まして、ます、ますれば、ませば、ましょう

Screenshot 2024-09-01 124617

2. Make んかった return `past` as out condition (make sure it's consistent with other かった ending), update name to '-n past'.

Will update some tests to make sure there are no false positives. 
Maybe we should have a refactor PR to update the language transform test logic too. Currently it only checks if a transformation is correct, it does not check if a term has any extra wrong transformation. For testing false positive, we have to know it in advance and explicitly add it to the test. This makes it hard to track the effect when we're adding new forms to the language.

### CODE REVIEW

**Comment by jamesmaa** [comment]
cc @lyroxide for review. If no review in 3 days I'll glance over it

**Comment by Lyroxide** [comment]
Any reason for including ませば? It's only used in kobun, where ませば is not "-ba of ます", but the "-ba of 未然形 of まし". I'd wager that ませば doesn't even exist in modern texts. ますれば seems fine though.

ませんかった threw me off at first but it seems legitimate according to 大辞林・日国

Is it possible to remove "-n past" but chain "-ta" with "-n"? Didn't had a chance to review when this was added initially.

**Comment by khaitruong922** [comment]
Thanks for review. Let's remove ませば for consistency since we are not going to include the まする form.

**Comment by khaitruong922** [comment]
I also agree with chaining `-n` -> `-ta` for `n-past.

ませんかった is the only exception `-n past`. It's not actually the `-n` form of verb, but just appending かった after ません.
I think the correct transformation would be `masu` -> `negative` -> `-ta`, instead of `-masu` -> `negative` -> `-n past` (having double negative transformation)

**Comment by khaitruong922** [comment]
Remove `n past`, added `-n` condition to chain with `-ta`.

**Review by jamesmaa — APPROVED** [review]

**Pull request merged**
