### PR TITLE
kbn-handlebars dependency update

### LINKED ISSUE #525: Anki templates should sanitize inputs from document.
It's worth noting that this html injection is currently an issue with the context.document.title as well, so coming up with a solution is probably worth doing. I tested it by setting the page title to `<script>alert(1)</script>` and then adding a card to anki with the `{document-title}` field and I got a popup with `1` in Anki when I opened the card.

As a solution to the above, we could just loop until there's no more html to strip. It's potentially O(n) but if we have a limit on the total context length then it's not that bad.
```js
function strip(html){
   let doc = new DOMParser().parseFromString(html, 'text/html');
   return doc.body.textContent || "";
}
var thing = "Just text <<a>script>alert('ciao');<</a>/script>"
while (strip(thing) !== thing) {
    thing = strip(thing);
}
console.log(thing);
```
This will just iterate until there's no more html to remove.

_Originally posted by @SnowySailor in https://github.com/themoeway/yomitan/issues/519#issuecomment-1891070194_

### PR DESCRIPTION
**Pull request by toasted-nutbread**
In lieu of elastic/kibana creating a npm package, how about we do something like this for this dependency? At the very least, this takes its code out of the repo and offloads any maintenance into a separate repo. Right now, it's referencing a repo that I set up, but it should realistically be something that is in themoeway's organization. If this works out, let me know if I can help with that.

Something else I've thought of a few times is that if it's possible to make handlebars support async functions, a _lot_ of the Anki note generation process could be able to be simplified. The fact that it's limited right now to being synchronous causes a lot of problems that make it difficult to add and maintain certain functionality. So that may lend to some justification of just hosting a fork of kbn-handlebars and potentially investigating to see if changes could be made to it that would help specifically this project.

This presumably resolves #525.
Should allow #529 to work.

### CODE REVIEW

**Comment by djahandarie** [comment]
Agreed that this is cleaner. I invited you as a member to themoeway github org, so once you accept that, you should be able to transfer the repo. I will also make sure the branch protections on it are set up properly, as that is basically our main security control for everything we do, and I'd like to make sure it's set up for all yomitan-related projects.

**Comment by toasted-nutbread** [comment]
Okay I've transferred the repo and updated the refs. I also updated the readme a little, but it's a little bit hard to attribute the same way as the others since it's a custom fork of a sub-folder of a mono-repo.

**Comment by djahandarie** [comment]
Thanks! Is that the output of `npm run license-report-markdown` or did you do it by hand? (I have no idea, as I've never seen its output for things pinned by hash)

**Comment by toasted-nutbread** [comment]
It's not, I didn't realize that's how that was generated. This is the output:

| Name                | Installed version | License type | Link                                             |
| :------------------ | :---------------- | :----------- | :----------------------------------------------- |
| @zip.js/zip.js      | 2.7.32            | BSD-3-Clause | git+https://github.com/gildas-lormeau/zip.js.git |
| dexie               | 3.2.4             | Apache-2.0   | git+https://github.com/dfahlander/Dexie.js.git   |
| dexie-export-import | 4.0.7             | Apache-2.0   | git+https://github.com/dexie/Dexie.js.git        |
| yomitan-handlebars  | 1.0.0             | MIT          | n/a                                              |
| parse5              | 7.1.2             | MIT          | git://github.com/inikulin/parse5.git             |
| wanakana            | 5.3.1             | MIT          | git+ssh://git@github.com/WaniKani/WanaKana.git   |

Which is not super meaningful for it, as I think it's always been version 1.0.0, and the n/a comes from me just directly cloning the folder contents without any metadata setup in package.json

**Comment by djahandarie** [comment]
@toasted-nutbread I think I'd prefer just sticking to the output of that command even if it's kind of useless. I think we should optimize for maintainability than having perfect legal references.

That said feel free to do whatever you want, I'll merge. (Just needs a merge conflict fix at least)

**Review by djahandarie — APPROVED** [review]

**Pull request merged**
