### PR TITLE
Rework dictionary import UX

### PR DESCRIPTION
**Pull request by Kuuuube**
Adds drag and drop functionality and the option to import dictionaries from a url.

### CODE REVIEW

**Comment by Kuuuube** [comment]
Fixed up the UI and added drag and drop functionality.

| Upon clicking `Import` | Dragging file |
| -|- |
| image | image |

**Comment by Kuuuube** [comment]
Current UI:

| Upon clicking `Import` | Dragging file |
| -|- |
| image | image |

I've also left in the `Import from URLs` option for now but it only appears if advanced settings are enabled.

**Comment by MarvNC** [comment]
If you can click the big button to open the file picker maybe the bottom button is redundant?

**Comment by jamesmaa** [comment]
My UI hot take: drag-and-drop is an advanced user feature and can actively work against most users' intuition of how to upload files. 

My [SWAG](https://en.wikipedia.org/wiki/Scientific_wild-ass_guess) is that 80% of users prefer Click to Upload over drag and drop.

Here are some examples of drag and drop UI's in other popular platforms:
Google drive: No indication it is supported but if you drag and drop into gdrive it works
image
FB: Indicates both options but prioritizes clicking the button first and de-emphasizes drag and drop
Screenshot 2024-05-15 at 9 08 17 PM
Github:
image
Youtube: Prioritizes drag and drop but adds a clear button to let users know a file browser is available as well
image


My suggestion is to go with FB's approach as it makes the upload file button much bitter and supports drag and drop for other users

**Comment by Kuuuube** [comment]
Current UI:

| Upon clicking `Import` | Hovering over with mouse | Dragging file | 
| -|- |- |
| image  | image | image |

**Review by jamesmaa — APPROVED** [review]
I didn't review the code details very carefully but this looks fine and looks well tested/polished and the breakage risk is low so :shipit:

**Pull request merged**
