### PR TITLE
Disable download button when dictionary is already installed

### LINKED ISSUE #1333: Recommended dicts still show as available to download even if they're already installed
**Description**
1. Install Jitendex
2. Refresh welcome page, click on recommended dicts, see that the Download button for Jitendex is still enabled

**Yomitan version**
24.8.19.0

### PR DESCRIPTION
**Pull request by khaitruong922**
Currently works for KANJIDIC and BCCWJ.
In `recommended-dictionaries.json`, Jitendex has its title hardcoded as `Jitendex`, but the title of it after installed from the recommended section is `Jitendex.org [2024-08-11]`. Don't know if we have control over the title of Jitendex,

image

Fixes #1333

### CODE REVIEW

**Comment by jamesmaa** [comment]
I'm honestly fine hardcoding for the Jitendex check

**Comment by khaitruong922** [comment]
Apart from dictionary `title`, how about checking for `downloadUrl` too? The url should be the same for Jitendex.

**Comment by Kuuuube** [comment]
We probably do need to keep the check for title. Not all dicts have a download url.

**Comment by khaitruong922** [comment]
My BCCWJ does not have a downloadUrl, so I think it's safe to check for both.

**Comment by MarvNC** [comment]
KANJIDIC has dynamic titles now though, are you sure?

**Comment by khaitruong922** [comment]
@MarvNC You're right. 
KANJIDIC and Jitendex should be disabled if installed after adding check for `downloadUrl`.

**Review by Casheeew — APPROVED** [review]

**Pull request merged**
