### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by jamesmaa**
- Introduce Microsoft Edge badge
- Change all the badge styles to be larger
- Remove OpenSSF Scorecard, kind of useless
- Remove "Changes" section. We've made over 900+ commits to Yomitan now, I would consider it stable

Preview 
image

### CODE REVIEW

**Review by MarvNC — APPROVED** [review]

**Review by Kuuuube — APPROVED** [review]

**Comment by djahandarie** [comment]
Is OpenSSF useless...? If the security of the repo degrades in some way (which is really trivial because it's so easy to make mistakes on GitHub due to its trash security UX), it could lead to something catastrophic like the the web store access keys being stolen and a malicious version of the extension getting pushed, followed by getting banned from the store.
It is important to have closed-loop control on security (aka having some sensor which someone is looking by at make sure things are okay instead of just hoping) so I recommend having this information highly visible somewhere.

**Comment by jamesmaa** [comment]
I agree security of the repo is really important. I'm not sure whether having a badge on the README is the right feedback loop to surface security issues. I haven't really looked at the OpenSSF badge and I doubt other people look at it either. If this is the only way to surface security issues in a timely manner, then I suppose we should put it back. But if there are other alternatives, maybe we can look at those.

It's low-cost UX cost to have it so ig I can put it back in the meantime while we pursue alternatives

**Comment by djahandarie** [comment]
Having a comment posted on PRs when the score decreases compared to master would be another nice feedback loop to have. Though I'm not sure if OpenSSF scorecard supports analyzing branches like that, it might only work on master. In which case it'd need to be a post-merge comment where it somehow finds the PR that caused the score drop in order to leave a comment there

**Comment by Kuuuube** [comment]
https://securityscorecards.dev/#use-cases

"Scorecard can be included in the continuous integration/continuous deployment processes using the GitHub action and run by default on pull requests."

They say it's possible.

**Pull request merged**
